"""Update attendance model to use composite key

Revision ID: 8500d6ba2c0e
Revises: a3b1ea6118ac
Create Date: 2025-07-15 13:07:22.370401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8500d6ba2c0e'
down_revision = 'a3b1ea6118ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_hours', sa.Float(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('ot_hours')

    # ### end Alembic commands ###
